name: 'Action'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore --no-cache

      - name: Build
        run: dotnet build --no-restore --configuration Debug

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Restore Test Dependencies
        run: dotnet restore /p:RestorePackagesConfig=true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          docker build -t my-app:staging .
          docker run -d -p 5000:80 --name my-app-staging my-app:staging

      - name: Set Staging URL
        id: deploy-staging
        run: echo "url=https://staging.example.com" >> $GITHUB_ENV

  production:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          docker build -t my-app:prod .
          docker run -d -p 80:80 --name my-app-production my-app:prod

      - name: Set Production URL
        id: deploy-production
        run: echo "url=https://production.example.com" >> $GITHUB_ENV
